class CreateProductTypes < ActiveRecord::Migration[8.1]
  def change
    create_table :product_types do |t|
      # What the operator calls it in the list. Free text, theirs.
      t.string :label, null: false

      # Where the structure lives. Split into the repository and the name
      # inside it, because both are needed separately: the name is what
      # soya-web-cli resolves, the repository is what the fetch talks to.
      t.string :repo_base_url, null: false
      t.string :structure_name, null: false

      # The DRI the repository answered with, if it gave one. Kept for the
      # record — a structure can be republished under the same name, and the
      # DRI is the only thing that says the cached copy is a different one.
      t.string :dri

      # The structure as fetched, and the author's YAML if the repository has
      # it. Plain text inside an encrypted file. This is what makes the
      # application work without a network afterwards: soya-web-cli is pointed
      # back at these rows rather than at the internet.
      t.text :jsonld
      t.text :yaml

      # JSON Forms, per language: {"de": {"schema":…, "ui":…, "options":…}}.
      # Generated by soya-web-cli at fetch time and kept, so that rendering a
      # form later needs neither the repository nor a second round trip.
      t.text :forms

      t.datetime :fetched_at
      t.string   :fetch_error

      t.timestamps
    end

    # One row per structure per repository. Two repositories may well publish a
    # "Lamp" and mean different things.
    add_index :product_types, %i[repo_base_url structure_name], unique: true
  end
end
